### ISSUE TITLE
Not able to load

### ISSUE THREAD

**Issue by awtsmoos** [Spiri0/Threejs-WebGPU-IFFT-Ocean-V2#1]
B"H

Tried copying all the code as is as of now to firebase hosting and get lots of errors right on start:

wave-cascade.js:259 Uncaught TypeError: Cannot set properties of null (setting 'value')
    at WaveCascade.Update (wave-cascade.js:259:57)
    at WaveGenerator.Update (wave-generator.js:120:34)
    at Entity.Update (entity.js:150:23)
    at EntityManager.Update (entity-manager.js:62:19)
    at Main.Step (main.js:197:29)
    at main.js:174:22
17
None of the supported sample types (UnfilterableFloat) of [Texture] match the expected sample types (Float).
 - While validating entries[1] as a Texture.
Expected entry layout: { binding: 1, visibility: ShaderStage::Compute, texture: { sampleType: TextureSampleType::Float, viewDimension: TextureViewDimension::e2D, multisampled: 0 } }
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
79
[Invalid BindGroup] is invalid.
 - While encoding [ComputePassEncoder].SetBindGroup(0, [Invalid BindGroup], 0, ...).
80
[Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])
awtsmoos3dexamples.web.app/:1 None of the supported sample types (UnfilterableFloat) of [Texture] match the expected sample types (Float).
 - While validating entries[4] as a Texture.
Expected entry layout: { binding: 4, visibility: ShaderStage::Compute, texture: { sampleType: TextureSampleType::Float, viewDimension: TextureViewDimension::e2D, multisampled: 0 } }
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
awtsmoos3dexamples.web.app/:1 None of the supported sample types (UnfilterableFloat) of [Texture] match the expected sample types (Float).
 - While validating entries[3] as a Texture.
Expected entry layout: { binding: 3, visibility: ShaderStage::Compute, texture: { sampleType: TextureSampleType::Float, viewDimension: TextureViewDimension::e2D, multisampled: 0 } }
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
8
None of the supported sample types (UnfilterableFloat) of [Texture] match the expected sample types (Float).
 - While validating entries[1] as a Texture.
Expected entry layout: { binding: 1, visibility: ShaderStage::Fragment, texture: { sampleType: TextureSampleType::Float, viewDimension: TextureViewDimension::e2D, multisampled: 0 } }
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
awtsmoos3dexamples.web.app/:1 [Invalid BindGroup] is invalid.
 - While encoding [RenderPassEncoder].SetBindGroup(0, [BindGroup], 0, ...).
﻿

![Screen Shot 2024-04-02 at 12 40 26 AM](https://github.com/Spiri0/Threejs-WebGPU-IFFT-Ocean-V2/assets/118651658/68e745ed-ac36-4bca-bae8-92571439e212)

**Comment by awtsmoos** [comment]
same with version 1 repo I mean actually

**Comment by Spiri0** [comment]
Ah, the reason is that your server is not cross-origin-isolated. Therefore, the SharedArrayBuffers are not supported in the worker and you don't get any ocean geometries.
Yes, the SharedArrayBuffers are a tricky thing. I really like SharedArrayBuffers as they are very powerful efficient tools. I have now redesigned the repo so that it should also work on a normal server, but I use a cross-origin-isolated server myself because that means I can use the SharedArrayBuffer.

**Comment by Spiri0** [comment]
Ah, the reason is that your server is not cross-origin-isolated. Therefore, the SharedArrayBuffers are not supported in the worker and you don't get any ocean geometries.
Yes, the SharedArrayBuffers are a tricky thing. I really like SharedArrayBuffers as they are very powerful efficient tools. I have now redesigned the repo so that it should also work on a normal server, but I use a cross-origin-isolated server myself because that means I can use the SharedArrayBuffer.
