### ISSUE TITLE
Live link

### ISSUE THREAD

**Issue by mrdoob** [Spiri0/Threejs-WebGPU-IFFT-Ocean-V2#2]
Any chance you can add live link to the project?
Maybe using `gh-pages`?

**Comment by Spiri0** [comment]
I've been meaning to do this for a long time, but I've been avoiding it so far because I don't know how to do it. The analyzes of the WebGPU issues have taken a lot of my time lately. I hope this will make Sunag's work easier. For transparent water so that you can see objects under the surface or the ground, I need depthTextures in the shader (light scattering for real impression). This is the issue #27502. I only found the cause of the problem two weeks ago, because in the meantime I was busy with another large threejs project. A fully-fledged threejs WebGPU virtual texture system at unreal engine level and since yesterday it has been working just as efficiently as I wanted it to. 
I actually developed this for huge landscapes in order to be able to use textures well beyond 100k, 1000k, ... for my real planetsize generator, but delicate models with complex structures are very suitable for tests.

![Arcadia (1).PNG](https://github.com/Spiri0/Threejs-WebGPU-IFFT-Ocean-V2/assets/69024222/1f75fe63-faef-45df-8cb6-e7b19020b7f0)


But back to the ocean. I'll try to find out how to do that. Or do you know how to do it? 

I'll take care of creating a new issue now. During my analysis of the extension of readRenderTargetPixelsAsync, I discovered something in the renderTargets. I know the cause of the problem and what to do to solve it. However, I have only recently started working with the threejs code myself, so I don't understand enough about it to be able to fix it myself.
Threejs is a great project, thank you ❤️

**Comment by Spiri0** [comment]
The problem with normal servers is that they are not configurable.
The ocean repo uses SharedArrayBuffers and for these I need cross-origin isolation or the coi-serviceworker to simulate it.

```
Server side:

Header set Access-Control-Allow-Origin "my repo site"
Header set Cross-Origin-Opener-Policy: same-origin
Header set Cross-Origin-Embedder-Policy: require-corp
```

The SharedArrayBuffers can be changed to ArrayBuffers. Let's see, I invited Manthrax because he has experience with using gh-pages. Maybe with a few changes it will work. It would be nice to be able to experience the ocean online

**Comment by Spiri0** [comment]
Ok I think I have it, try your luck 😊
I should then also reduce the resolution a little so that it is not so computationally intensive. That would still look good.
