### ISSUE TITLE
Broken render on Macbook M1 Pro

### ISSUE THREAD

**Issue by mrdoob** [Spiri0/Threejs-WebGPU-IFFT-Ocean-V2#4]
https://github.com/Spiri0/Threejs-WebGPU-IFFT-Ocean-V2/assets/97088/bc3e5a55-3821-4ae6-b036-87ef1720876a

Chrome 124.0.6367.156

**Comment by Spiri0** [comment]
That looks pretty ugly. Is there an error message in the console?
Unfortunately I don't have a Macbook. I have to think about whether I know anyone who has one

**Comment by mrdoob** [comment]
> That looks pretty ugly. Is there an error message in the console?

Hmm, there is!

<img width="657" alt="Screenshot 2024-05-07 at 7 23 26 PM" src="https://github.com/Spiri0/Threejs-WebGPU-IFFT-Ocean-V2/assets/97088/6acde029-4d1a-434e-b9b6-275d95ae7615">

**Comment by Spiri0** [comment]
The warning with the “normal” not found on geometry is harmless. This is because I save the creation of the normal attribute in the worker for the geometry, since the normal vectors come from the IFFT derivations. I'll still create normals even if they won't be used anyway. Then the warning is gone.

The one with the timeout I have never seen.

Can you please make a test in main in the RAF function:

//setTimeout(() => {
     this.RAF();
//}, 1);

because the timeout is not neccessay. I've already taken that out of mine. This has become an unnecessary relic.

**Comment by mrdoob** [comment]
@sunag Any ideas?

**Comment by sunag** [comment]
> @sunag Any ideas?

No yet... M2 and Windows it work done.

**Comment by Spiri0** [comment]
It also works without any problems on my desktop with Ubuntu with r161 to r164. I have to go to work now. I'll try to update to r164 ​​this evening. This probably won't solve the problem, but it still makes sense. Then I can also use "await renderer.init();"

**Comment by Spiri0** [comment]
I have now updated to r164. And I also made sure that the warning about the missing normal vectors no longer appears by now creating normal vectors for the buffer geometries. In addition, the app is now initialized robustly.

Unfortunately I can only test this on the devices I have. This is my windows laptop and my ubuntu desktop. It runs well on both.

What about your Macs?

**Comment by mrdoob** [comment]
Turns out this is a bug in MacOS that has already been fixed in 14.5 👌
