### ISSUE TITLE
Weird rendering on windows 11

### ISSUE THREAD

**Issue by ghost** [Spiri0/Threejs-WebGPU-IFFT-Ocean-V2#6]
I tried your website on my edge browser this looks something like this

![image](https://github.com/Spiri0/Threejs-WebGPU-IFFT-Ocean-V2/assets/169458325/2af1f8fb-37e5-4b51-adf9-2c1ad9ed1931)

The console is all clear no message is there

**Comment by Spiri0** [comment]
Hi codexsr, 
This reminds me of the issue mrdoob had:

https://github.com/Spiri0/Threejs-WebGPU-IFFT-Ocean-V2/issues/4

The picture suggests that the WGSL shaders are not being processed correctly by the system.
In some browsers on certain systems, WebGPU is not yet fully supported. The fact that something like this doesn't even produce an error message in the console indicates that the browser in the system in question does not fully support it, otherwise you would expect an error message because it is obviously not right.

It works in Windows 10 in Chrome and Edge. On my Ubuntu computer with Chrome too. Since it works in general, it is something system-specific. However, the fact that there is no error message in the console is annoying because I could at least identify the cause.

Unfortunately, without a trace, we can only speculate 😔
Have you already been able to test it with Chorme on the same computer? I'm asking specifically about chrome because chrome offers the best support for WebGPU so far.
For some systems, Chrome only started supporting WebGPU this year. I find it exciting to experience this new technology from the very beginning.
